---

-   name: Install elastic search on docker
    docker_compose:
        project_name: elasticsearch
        definition:
            version: '3'
            services:
                elasticsearch:
                    image: "docker.elastic.co/elasticsearch/elasticsearch:{{ elasticsearch_version }}"
                    container_name: elasticsearch
                    restart: unless-stopped
                    ports: "{{ elasticsearch_ports }}"
                    environment:
                        - discovery.type=single-node
                        - xpack.security.enabled=false
                        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"            
    tags:
        - elastic-search